{
 "title": "Query 2",
 "time": { "from": "2020-01-21T08:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Mean of cured by continent",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Africa",
     "measurement": "query2_mean_Africa",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "America",
     "measurement": "query2_mean_America",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Asia",
     "measurement": "query2_mean_Asia",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Europe",
     "measurement": "query2_mean_Europe",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Oceania",
     "measurement": "query2_mean_Oceania",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Antarctica",
     "measurement": "query2_mean_Antarctica",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Standard deviation of cured by continent",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Africa",
     "measurement": "query2_stddev_Africa",
     "select": [
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "America",
     "measurement": "query2_stddev_America",
     "select": [
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Asia",
     "measurement": "query2_stddev_Asia",
     "select": [
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Europe",
     "measurement": "query2_stddev_Europe",
     "select": [
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Oceania",
     "measurement": "query2_stddev_Oceania",
     "select": [
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Antarctica",
     "measurement": "query2_stddev_Antarctica",
     "select": [
      [
       { "params": [ "stddev" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max of cured by continent",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Africa",
     "measurement": "query2_max_Africa",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "America",
     "measurement": "query2_max_America",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Asia",
     "measurement": "query2_max_Asia",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Europe",
     "measurement": "query2_max_Europe",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Oceania",
     "measurement": "query2_max_Oceania",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Antarctica",
     "measurement": "query2_max_Antarctica",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min of cured by continent",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Africa",
     "measurement": "query2_min_Africa",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "America",
     "measurement": "query2_min_America",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Asia",
     "measurement": "query2_min_Asia",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Europe",
     "measurement": "query2_min_Europe",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Oceania",
     "measurement": "query2_min_Oceania",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Antarctica",
     "measurement": "query2_min_Antarctica",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}